### ISSUE TITLE
Reflection Free Configuration and Proguard

### ISSUE THREAD

**Issue by philipbjorge** [stephanenicolas/toothpick#146]
Is there any guidance on how to use the reflection free configuration with proguard and obfuscation?
Based on looking at the factories, it looks like I'll need to keep my class names at a minimum (possibly method names too).

`-keepnames class com.myapp.**`

Do you have any advice on how I can make this more specific?

**Comment by philipbjorge** [comment]
Here's what I've got working on my project...

```
-keep class javax.inject.**

# Do not obfuscate annotation scoped classes
-keepnames @javax.inject.Singleton class *
# Add any custom defined @Scope (e.g. @Singleton) annotations here
# because proguard does not allow annotation inheritance rules

# Do not obfuscate classes with Injected Constructors
-keepclasseswithmembernames class * {
    @javax.inject.Inject <init>(...);
}

# Do not obfuscate classes with Injected Fields
-keepclasseswithmembernames class * {
    @javax.inject.Inject <fields>;
}

# Do not obfuscate classes with Injected Methods
-keepclasseswithmembernames class * {
    @javax.inject.Inject <methods>;
}
```

**Comment by dlemures** [comment]
Hi @philipbjorge ,

Thanks for the rules!

Do you need `-keep class javax.inject.**`? 
As we used them just at compile time as far as i remember.

**Comment by stephanenicolas** [comment]
As soon as @philipbjorge answers our question, we should add this to the wiki page about configurations.

**Comment by philipbjorge** [comment]
@dlemures When I remove the `-keep class javax.inject.**`, I get the following error at runtime:

```
Unable to start activity ComponentInfo{com.xyz/com.xyz.activities.MainActivity}: e.c.e: No factory could be found for class com.xyz.a.a. Check that the class has either a @Inject annotated constructor or contains @Inject annotated members. If using Registries, check that they are properly setup with annotation processor arguments.
android.app.ActivityThread.performLaunchActivity
```

Any ideas why or how to debug?

**Comment by philipbjorge** [comment]
Looking at my stacktraces + mappings.txt makes me think something real funny is going on.
I'll keep digging and might be able to remove the javax.inject rule...

**Comment by philipbjorge** [comment]
OK, so I had the following rule to keep the names of all the classes annotated with my custom scope annotations
`-keepnames @com.xyz.support.di.scopes.* class *`

Turns out that doesn't work and you need to list them all out manually
```
-keepnames @javax.inject.Singleton class *
-keepnames @com.xyz.support.di.scopes.ActivitySingleton class *
-keepnames @com.xyz.support.di.scopes.FragmentSingleton class *
-keepnames @com.xyz.support.di.scopes.ChildFragmentSingleton class *
```

Now I'm running into a new issue though. Will update shortly.

**Comment by stephanenicolas** [comment]
Yes, probably the best here would be to recommend not to obfuscate any project class...

**Comment by stephanenicolas** [comment]
solved by https://github.com/stephanenicolas/toothpick/wiki/Proguard-&-TP

**Comment by markchristopherng** [comment]
we recently migrated to toothpick from roboguice and these proguard rules worked on our project

-keepattributes *Annotation*

-keepnames class * {
	@javax.inject.Inject <init>(...);
	@javax.inject.Inject <fields>;
	@javax.annotation.Nullable <fields>;
}
# Do not obfuscate annotation scoped classes
-keepnames @javax.inject.Singleton class *
-dontwarn javax.inject.**

# generated toothpick classes
-keep class **$$Factory{ *; }
-keep class **$$MemberInjector{ *; }

**Comment by L7ColWinters** [comment]
wait, so the solution to this is not to obfuscate the code?! Most production applications require some form of obfuscation for a semblance of security. This seems like a major dealbreaker and i'm only saying that because I'm having trouble with the above proguard rules. It would have been nice to have a solution that included a recommended (Tested and true) way of using proguard with the library.

**Comment by stephanenicolas** [comment]
All names of classes using injection won't be obfuscated.

We use this at Groupon, not only because of toothpick but because of quite
a few other librairies that rely on some naming convention to.load classes
to avoid reflection. For instance ButterKnife, Dart, Icepick, etc. Dagger 1
or 2 would be no exception here.

As you say, obfuscation provides kind of a feeling of secrecy, not much
more. So, what else could a library offer ?

Also, besides name obfuscation, you can also use other proguard
transformations like optimization, method rewriting, etc that will probably
provide even further hard to decompile byte code.

We are really not sure about what TP itself removes to apps on this matter.
And we would be happy to hear from a better solution.

**Comment by terrakok** [comment]
@stephanenicolas  
We need setup ProGuard with 
https://www.guardsquare.com/en/proguard/manual/usage#adaptclassstrings
For changing class names in `FactoryRegistry`

**Comment by stephanenicolas** [comment]
Thx for hint @terrakok. If anyone feels like adding a proguard configuration page to TP wiki, feel welcome to do so.

**Comment by pshmakov** [comment]
@stephanenicolas 
@terrakok 
adaptclassstrings **almost** works (with registries).
The only problem is that switch statement doesn't work for equal strings that have undergone this proguards "adaptation". Don't ask me why.
So this code:
`switch("com.smth.Smth") {
    case "com.smth.Smth":
        return true;
}
return false;`
returns true before obfuscation and false after obfuscation with -adaptclassstrings.

Whatever the reason, the solution is simple: just generate if-else chain instead of switch. I checked that it works.

**Comment by stephanenicolas** [comment]
@pshmakov the problem is that it would be slower, that's the main reason why we have the switch.

Can you give an example of the code after it is obfuscated so we can fine tune this ?

**Comment by pshmakov** [comment]
@stephanenicolas 
Indeed, switch is faster, and the optimization that makes it faster is the one that causes problems with obfuscation.
I'm not sure what you mean by "example of the code after it is obfuscated". If I understand it correctly, obfuscation is applied to the bytecode, not the source code. Pretty much any Toothpick sample would exhibit the problem with obfuscation; I use this sample for experimenting: https://bitbucket.org/Con_Fuoco/toothpick-demo/overview

**Comment by pshmakov** [comment]
@stephanenicolas
I updated my patch, so that a HashMap is generated instead of switches or ifs. The lookup time should be roughly the same as before, but there is some extra memory usage, which I think shouldn't be critical: those factories are lightweight, they don't have any fields at all.
The change only affects the case when "support_obfuscation" annotation processing parameter was set to "true". Otherwise it will generate switches as before.

I'd like to point out that this issue seems to be a "blocker" for using ToothPick in a large portion of commercial projects, because using obfuscation there is absolutely non-negotiable. I work on one of such projects, and would really like to give Toothpick a shot, because it's awesome. But this issue needs to be fixed first. Otherwise we'll have to go with Dagger 2, unfortunately (which doesn't have problems with obfuscation as far as I know).

**Comment by terrakok** [comment]
@stephanenicolas  
What do you think about PR?

**Comment by pshmakov** [comment]
So, we have the patched toothpick up and running in production, everything seems working fine.
Until the PR is merged or some other solution comes around, here is the temporary one:
1) Use patched annotation processor built from the fork:
   `annotationProcessor files('libs/toothpick-compiler-1.1.3-obfuscation-fixed.jar')`
    `annotationProcessor 'com.squareup:javapoet:1.4.0'`  
    `annotationProcessor 'javax.inject:javax.inject:1'`

Or kapt if you use kotlin.
The file is attached.

2) Use configuration with registries: https://github.com/stephanenicolas/toothpick/wiki/Factory-and-Member-Injector-registries
3) Add `toothpick_obfuscation_support : "true"` to annotation processor options (along with `toothpick_registry_package_name`)
4) Add `adaptclassstrings **` to proguard rules.

[toothpick-compiler-1.1.3-obfuscation-fixed.zip](https://github.com/stephanenicolas/toothpick/files/1777733/toothpick-compiler-1.1.3-obfuscation-fixed.zip)

**Comment by stephanenicolas** [comment]
This is adressed in TP 1.1.3, released today.
