### ISSUE TITLE
AutoCloseable / freeing up resources

### ISSUE THREAD

**Issue by kanawish** [stephanenicolas/toothpick#179]
I've got an Android project with an Activity-scoped dependency that contains a few resources I need to explicitly release when closing the scope down.

I've found some vague hints online that using something like `AutoCloseable` to flag end-of-life for objects in a DI's scope might be a possible avenue. 

What would be your thoughts on this as a feature for Toothpick?

**Comment by stephanenicolas** [comment]
Hi Etienne,

nice to hear from you. It's been a while since we met in Montreal. How di ?

Regarding your issue, I am not sure to understand: if you need the
resources to be closed as you close the scope, why don't you do it at the
same time ? I mean, the activity closing the resources..

In our app, we somewhat achieve a similar thing without DI: when an
activity closes, it emits a Rx item from within a subject to wish we need
to subscribe beforehand, like an event bus if you like.

`AutoCloseable` is not part of TP, and it's not an annotation prescribed in
JSR 330 neither. I never heard of anything like that.

We don't really feel the need for this feature, but it could make sense. At
some point we had planned it, but then realized quickly that this could be
achieved by other means and that actually emitting events for all things in
TP (generalizing the event for closing a scope), would be a long task. But
it's open source and PRs are welcome ;)

Cheers,
S.

2016-12-08 9:16 GMT-08:00 Etienne Caron <notifications@github.com>:

**Comment by stephanenicolas** [comment]
Issue is closed has the feature is not desired and there is no update.
