### ISSUE TITLE
Multiple singletons when retrieved with different class keys

### ISSUE THREAD

**Issue by GisoBartels** [stephanenicolas/toothpick#185]
Hi there,

I recently encountered a subtle bug, where I ended up with two instances of a singleton. During a refactoring I introduced an interface to a singleton class. Older parts of the code are still injected with the class, newer parts are using the interface, which is bound to that implementation class.
I wrote some unit tests to illustrate this issue: [Commit 512107c](https://github.com/GisoBartels/toothpick/commit/512107c0bc384bad2dc685092fb58e558c02892e)

I am not quite sure about the best course of action here. Maybe the generated factory should cache the instance for singletons instead of always creating a new instance?

P.S. Keep up the good work :thumbsup:

**Comment by stephanenicolas** [comment]
This is not a bug and I don't see any workaround that could make sense.

By creating to bindings, they get converted to 2 internal providers in TP. And both of them will use the singleton implementation class's factory to create a different instance. 

The problem here is to use 2 bindings for a singleton using the `to(impl.Class)` bindings. For instance, using an instance of the singleton, manually constructed, and then associating it to both key classes would work. Here there is nothing we can do really. Devs should simply not do that. But I agree it's not easy to get and it requires some knowledge of TP internals to understand what happens.

The only thing we could do would be to detect this situation in a check at runtime for the development config. But it will quickly become very very very complicated to intercept that for all possible cases. I don't think it can even fully make sense. 

It s good we have a ticket in case people face the same issue but I can't find any workaround.

**Comment by cbeyls** [comment]
One solution I found to have the same singleton instance bound to different types in Toothpick is to declare a `Provider` for each extra type, where the base type is injected in the constructor of the `Provider` and the `get()` method simply casts it to the correct type and returns it.

**Comment by stephanenicolas** [comment]
Yes, that's the right way to do it. Thx. FYI: this is a duplicate of https://github.com/stephanenicolas/toothpick/issues/327
