### ISSUE TITLE
Async providers

### ISSUE THREAD

**Issue by dlemures** [stephanenicolas/toothpick#213]
Investigate async providers

**Comment by stephanenicolas** [comment]
http://google.github.io/dagger/producers.html

I am not really convinced by the relevance of this feature. We had some futures at some point in TP codebase as well. But we decided to remove it because it was enlarging the scope of the library, and this holds true as well for Dagger 2. 

Personally, I don't think a DI lib should take care of this, and it can actually be done in a cleaner way via Rx Java for instance, using reusable pools and limiting the adherence to the lib to concurrency APIs.

@dlemures, what do you think if you close the issue ?

Thx to Евгений from Mobius 2017 for mentioning the issue.

**Comment by katella** [comment]
@stephanenicolas, you're welcome :) Actually I asked this question only because of curiosity. In my opinion, this feature is too specific and it certainly will make your library too "heavy". Toothpick looks awesome because it's simple and works absolutely transparently. So I wish you to keep it this way.

**Comment by stephanenicolas** [comment]
Thx @katella for pointing out this feature though. I close the issue. See you around !
