### ISSUE TITLE
Collaboration of TP with new Android ViewModel

### ISSUE THREAD

**Issue by afaucogney** [stephanenicolas/toothpick#265]
When using both TP and android viewModel, it appear that both technologies manage scopes or scope-like.

Anyone already experimented integration of both ? 

As I understood, ViewModel offer a kind of behavior that may be understood as ActivityScope. How may we insure to not having any interference ?

I bind the ViewModel like this:
       bind(ISplashActivityContract.ViewModel::class.java).toInstance(ViewModelProviders.of(this@SplashActivity).get(SplashActivityViewModel::class.java))

Is it sufficient ?

Is there anything special when dealing with viewmodel instance share between fragment ?

**Comment by stephanenicolas** [comment]
ViewModel provides a scope that is between Application and activity scopes
in TP, what we call a flow scope. This scope will survive the activity
rotation / config changes.
There is no real interference if you don't use a flow scope or if you don't
use all parts of the ViewModel. Also, it is possible to customize the
ViewModel to use TP, I don't remember where exactly but there is a way to
pass a custom something factory to a ViewModel and use a TP scope there.

The main thing is, whatever you choose, don't keep a reference of your
activity instances in the view model / flow scope, they would leak.

We are not big fans of the ViewModel or the arch components because other
tools are more powerful (LiveData Vs Rx, ViewModel Vs TP Scopes, etc.). But
we might be biased ;)
Just to say that we probably won't be of much help here.

Your binding seems correct. Not sure what you mean by "this@SplashActivity"
though.

There is nothing special about fragments.


2017-10-31 14:21 GMT+00:00 Faucogney Anthony <notifications@github.com>:
