### ISSUE TITLE
Bind modules that depends on each other [question]

### ISSUE THREAD

**Issue by WarrenFaith** [stephanenicolas/toothpick#274]
_I do not want to spam but it seems on SO there are barely any questions regarding toothpick so I hope to get some feedback if I cross post my qestion here:_

I created the following [test project on github](https://github.com/WarrenFaith/Toothpick-Sample/tree/test/simple_injection) where I tried to make a smallest possible use case for my understanding issue.

There you will find the [ApplicationModule](https://github.com/WarrenFaith/Toothpick-Sample/blob/test/simple_injection/app/src/main/java/com/example/toothpicktestproject/ApplicationModule.java) where I try to inject everything I need in my "root" module. As you can see there, I have twice `scope.installModules(module)` because my `PlainPojo` depends on the `Application` instance. If I do not do the first `installModule` call, I have no application instance in the scope. I could, as mentioned in the comment, pass the application instance as a parameter but I thought that I can remove them when I use DI?

The second class that causes troubles is the [SimpleTest](https://github.com/WarrenFaith/Toothpick-Sample/blob/test/simple_injection/app/src/main/java/com/example/toothpicktestproject/simpletest/SimpleTest.java) class. If I do not call the `inject()` method in the constructor, the PlainPojo member will not be injected. I also tried to use a third time the `installModules()` in the `ApplicationModule` after binding the PlainPojo but that does not help.

Am I so wrong to assume that an `@Inject` on a member is enough to automatically inject it when it is available in the scope and that the order of binding is enough to make previous bindings available without installing in between (like done in `ApplicationModule`)?

If I can provide anything more to make my issue(s) understandable please leave a comment.

Thanks in advance!

Source (and if you want to get some reputation on SO)
https://stackoverflow.com/questions/48298189/toothpick-bind-modules-that-depends-on-each-other

**Comment by stephanenicolas** [comment]
Hi @WarrenFaith , there are a few things you could do to make your code better:

Don't call module something that is not a module. So we will create a true module class, this module will be created by hand, we will pass the app to it as a parameter.
```
class AppModule extends Module {
    private Application app;
    public AppModule(Application app) {
      this.app = app;
      bind(Application.class).toInstance(app);
}
```
That's it, the rest can now work much more automatically. All you will do is to instanciate the module in the Application class and install it on the TP Application scope.

To create your "plain pojo" (bad name, a pojo is a simple data structure, it does no logic work and should not need the app), just pass the app as a parameter to an injected constructor:

```
class PlainPojo{
  private Application app;

  @Inject 
  public PlainPojo(Application app) {
    this.app = app;
  }
}
```
When you do this, TP will know that, as soon as you do `@Inject PlainPojo`, it will need to pass the app to create the instance, and TP will know which app we are talking about because it has a binding for it.

Same goes for the simple test class:
```
class SimpleTest{
  private PlainPojo pojo;

  @Inject 
  public SimpleTest(PlainPojo pojo) {
    this.pojo = pojo;
  }
}
```
TP can chain the dependencies, if you `@Inject SimpleTest` somewhere, it will create the plain pojo needed and pass it the app needed.

And finally, instead of your custom application module, you can use the ApplicationModule provided by ToothPick's smoothie component. It does exactly the same and adds a few more useful bindings.

**Comment by stephanenicolas** [comment]
I close this issue. Sorry that we didn't monitor SOF more closely.

**Comment by dimsuz** [comment]
I have also asked a toothpick-related question on StackOverflow and it still doesn't have an answer or comment, more than a week has passed.

Decided to ping you guys here, maybe someone will have time to check it out and give me some advice.

Here's the question: 
https://stackoverflow.com/q/49412905/258848
