### ISSUE TITLE
Support Incremental Annotation Processing in Gradle 4.7+

### ISSUE THREAD

**Issue by yogurtearl** [stephanenicolas/toothpick#290]
Support Incremental Annotation Processing in Gradle 4.7+
https://docs.gradle.org/nightly/userguide/java_plugin.html#sec:incremental_annotation_processing

I saw the comment [here](https://github.com/google/dagger/issues/1120), but didn't see an issue for it, so filing one. :)

**Comment by oehme** [comment]
Just a quick heads-up: In Gradle 4.8 the registration mechanism will change to be [processor option based](https://github.com/gradle/gradle/pull/5255) instead of META-INF based, as suggested by the AutoValue team. The META-INF way will still work till 5.0, but be ignored afterwards. 

Also in 4.8 Gradle will no longer fail compilation if a processor does something unsupported, but just do a full recompile instead. That should make things more robust.

Is there anything else I can do to move this forward?

**Comment by autonomousapps** [comment]
Any update on this?

**Comment by stephanenicolas** [comment]
Not yet. But it shouldn't be very long.

TP 2 will definitely address that.

**Comment by stephanenicolas** [comment]
TP 2 definitely addresses that :) :) :) :)
