### ISSUE TITLE
toothpick.locators.NoFactoryFoundException

### ISSUE THREAD

**Issue by Riningan** [stephanenicolas/toothpick#340]
Hello!

I my android application sometimes has crash:

```kotlin
toothpick.locators.FactoryLocator.getFactory + 21 (FactoryLocator.java:21)
--
  | toothpick.ScopeImpl.lookupProvider + 329 (ScopeImpl.java:329)
  | toothpick.ScopeImpl.getInstance + 58 (ScopeImpl.java:58)
  | toothpick.ScopeImpl.getInstance + 49 (ScopeImpl.java:49)
  | com.b2b_logist.smarttracker.presentation.ui.history.HistoryNewsListener__Factory.createInstance + 12 (HistoryNewsListener__Factory.java:12)
  | com.b2b_logist.smarttracker.presentation.ui.history.HistoryNewsListener__Factory.createInstance + 8 (HistoryNewsListener__Factory.java:8)
  | toothpick.InternalProviderImpl.get + 96 (InternalProviderImpl.java:96)
  | toothpick.ScopedProviderImpl.get + 31 (ScopedProviderImpl.java:31)
  | toothpick.ScopeImpl.getInstance + 58 (ScopeImpl.java:58)
  | toothpick.ScopeImpl.getInstance + 49 (ScopeImpl.java:49)
  | com.b2b_logist.smarttracker.presentation.ui.history.HistoryBinding__Factory.createInstance + 15 (HistoryBinding__Factory.java:15)
  | com.b2b_logist.smarttracker.presentation.ui.history.HistoryBinding__Factory.createInstance + 8 (HistoryBinding__Factory.java:8)
  | toothpick.InternalProviderImpl.get + 94 (InternalProviderImpl.java:94)
  | toothpick.ScopeImpl.getInstance + 58 (ScopeImpl.java:58)
  | toothpick.ScopeImpl.getInstance + 49 (ScopeImpl.java:49)
  | com.b2b_logist.smarttracker.presentation.ui.history.HistoryFragment__MemberInjector.inject + 11 (HistoryFragment__MemberInjector.java:11)
  | com.b2b_logist.smarttracker.presentation.ui.history.HistoryFragment__MemberInjector.inject + 8 (HistoryFragment__MemberInjector.java:8)
  | toothpick.InjectorImpl.inject + 23 (InjectorImpl.java:23)
  | toothpick.Toothpick.inject + 163 (Toothpick.java:163)
  | com.b2b_logist.smarttracker.presentation.ui._base.BaseFragment.onCreate + 44 (BaseFragment.kt:44)
``` 

Inject look like this:

```kotlin
    override fun onCreate(savedInstanceState: Bundle?) { // BaseFragment
        Logger.forThis(this).debug()
        super.onCreate(savedInstanceState)
        retainInstance = true
        Toothpick.openScopes(
                App::class.java.canonicalName,
                MainActivity::class.java.canonicalName,
                MainActivity::class.java.simpleName,
                this.javaClass.canonicalName).let {
            it.installModules(module)
            Toothpick.inject(this, it) // BaseFragment.kt:44
        }
    }
```

Toothpick can't inject field that identified in SessionModule. Session module installs in MainActivity 

```kotlin
    override fun attachBaseContext(newBase: Context?) { // MainActivity 
        Logger.debug()
        super.attachBaseContext(newBase)
        // di
        Toothpick.openScopes(App::class.java.canonicalName, this.javaClass.canonicalName).installModules(SessionModule())
        Toothpick.openScopes(App::class.java.canonicalName, this.javaClass.canonicalName, this.javaClass.simpleName).let {
            it.installModules(SmoothieAndroidXActivityModule(this), ActivityModule(this))
            Toothpick.inject(this, it)
        }
    }
```

That I'm doing wrong?

**Comment by stephanenicolas** [comment]
Hi @Riningan ,

there are a few things : 
* App::class.java.canonicalName --> do not use the class names here. Use the application object and the activity objects themselves as name. When an object has a lifecycle and you want to create a scope that has the same lifecycle, use this object as a name for the associated scope. Not a class name.  --> `TP.openScopes(application, this)`
* I don't understand why you have 3 levels of scopes. Are you trying to create a scope that survives the activity rotation ? If so, please have a better look at the example, you have to create a **scope annotation**, and use the classname of this scope annotation as the name of the second scope. You will also use the scope annotation to annotation things your session module.
* I would recommend to open the scopes, store the result in a variable, use the scope to install the 2 modules (you can pass an array/varargs of modules). And last, inject(this) using this scope. 
* also, as you seem to be using a retained fragment, I am not sure exactly of what you are trying to achieve with the scopes: do you really want to have 4 different scopes ? Try to stick to 3 scopes for now, if you really need a scope that surives the activity, otherwise, 2 is good.
* finally open HistoryNewsListener__Factory, line 12. Look at the class that is injected. Check if a factory was generated, maybe you forgot to annotate the type to make it injectable.

Re-open as needed, but I would suggest to take more time to go through the docs and examples first.

**Comment by Riningan** [comment]
Hi @stephanenicolas ,

Thanks about help. But I have a question about second advice. How I can annotate class of third party? This class I using in session scope.

**Comment by stephanenicolas** [comment]
You can't annotate a class if you don't have the code..
But you can create a binding in the scope where you want it to leave, a binding with a provider seems best in this case.

**Comment by Riningan** [comment]
Can you help me? I don't understand how create provider class in my case.
I need to store this field in presenter (session) scope
```kotlin
val router = Router()
val cicerone = Cicerone.create(router)
bind(Router::class.java).toInstance(router)
bind(NavigatorHolder::class.java).toInstance(cicerone.navigatorHolder)
```
If I understand you, you mean create:
```kotlin
@SessionScope
class ThirdPartyProvider @Inject constructor() {
    fun getSomethinkThirdParty() : SomethinkThirdParty = SomethinkThirdParty()
}
```
and inject like this?
```kotlin
@Inject
lateinit mThirdPartyProvider ThirdPartyProvider
```

**Comment by dlemures** [comment]
> I need to store this field in presenter (session) scope

If the above sentence means that you want it to be a Singleton on the session scope, you should do something like this:

```kotlin
@SessionScope @Singleton
class SomethinkThirdPartyProvider : Provider<SomethinkThirdParty> {
    override public get() = SomethinkThirdParty()
}
```
Then install a module on that Scope with the following binding
```kotlin
bind(SomethinkThirdParty::class.java).toProvider(SomethinkThirdPartyProvider::class.java)
```

And then you should be able to inject the same instance anywhere using that scope or any child scope:
```kotlin
@Inject
lateinit var SomethinkThirdParty somethinkThirdParty
```

**Comment by Riningan** [comment]
Thanks a lot!
