### ISSUE TITLE
Could we have some explanation about @InjectConstructor

### ISSUE THREAD

**Issue by afaucogney** [stephanenicolas/toothpick#354]
Hi, after reviewing the tp3 sample, I saw @InjectConstructor in 2 classes. What is the purpose of this new annotation ?

**Comment by stephanenicolas** [comment]
Hi @afaucogney , we are working on a migration guide for TP3. Is this documentation correct: https://github.com/stephanenicolas/toothpick/wiki/TP-2---TP-3:-Migration-Guide#new-annotations ? If so, please feel free to close this issue.

**Comment by afaucogney** [comment]
Ok thanks Stephanie, I was expecting this answers. but could you tell us
why you did this ? What was the intention ?
Because I like the idea to use the standard annotation, it makes the
project less depending on di framework (even if I like much tp), especially
if it brings no added value. What do you think, or what is you position on
this point ?

PS : I know I can still use the original annotation ;)

Le mar. 6 août 2019 à 18:01, Stéphane Nicolas <notifications@github.com> a
écrit :

**Comment by dlemures** [comment]
Hi @afaucogney ,

First of all, thx for having a look at the new version this fast!

Regarding the `@InjectConstructor` annotation, it is some syntactic sugar on top of `@Inject` to make Toothpick less intrusive for Kotlin. Some facts about it:

1. It is equivalent to use `@Inject` on the constructor:
```kotlin
@InjectConstructor
class MyDependency(val myHelper: MyHelper)
```
is the same as
```kotlin
class MyDependency @Inject constructor(val myHelper: MyHelper)
```
So if you prefer to use the standard annotation `@Inject`, you can do it.

2. As I mentioned before, the value that it provides is to make it possible to make a class "injectable" without having to change your language coding style. As you could already do with Java just by using `@Inject`.

3. Because of `(1)`, `@InjectConstructor` will propagate the injection to the transitive dependencies. So `myHelper` will be injected inside `MyDependency` and so on...

**Comment by stephanenicolas** [comment]
@afaucogney please re-open if needed. Thx for the question.
