### ISSUE TITLE
Classes generated in the last round, so they are not processed

### ISSUE THREAD

**Issue by dlemures** [stephanenicolas/toothpick#85]
Some classes are generated in the last round, so they are not processed.

Example:
```
[ERROR] [system.err] warning: File for type 'toothpick.data.FooWithProvider$$MemberInjector' 
created in the last round will not be subject to annotation processing.
```

**Comment by stephanenicolas** [comment]
http://stackoverflow.com/a/16114496/693752

In our case I think we can create the code in the first round even.

No generated code, AFAIK, is gonna be annotated with "our" annotations so we will see all files to parse in the first round if my understanding is correct.

The ideal fix would be to create any needed new generated code during each stage.

**Comment by eygraber** [comment]
Is this why `MemberInjectorRegistry` and `FactoryRegistry` have to be fully qualified instead of being imported?

**Comment by atomd** [comment]
+1

**Comment by stephanenicolas** [comment]
I didn't get what you mean. This issue is about à warning message during
annotation processing. Nothing big.

The problème you mention is about how the IDE deals with generated code.

**Comment by stephanenicolas** [comment]
There is nothing we can do against this warning because it would break the possibility for any OTHER annotation processor to generate code using @Inject.

Annotation processing rounds are constructed this way: 
* first an annotation processing round will report all annotations being used in the source code.
* if an annotation processor generates code, and this contains annotations, then a second round is constructed and it reports these annotations. 
* and so on
* until there is no more new annotations to be reported, then a last round is constructed.

We can be optimistic and generate MemberInjectors and Factories during every round of annotation processing. That would work as all annotations in the each source file are supposed to be reported during the same round. 

But to generate the registries, we still need ALL member injectors or factories. So if there is any OTHER annotation processor that generates code using @Inject annotations, we woud need to add their registries and factories. The only appropriate place to generate the registries is last round.

We also tried to use a trick mentioned in : http://stackoverflow.com/a/16114496/693752
But it doesn't work: if we create the registries as resource files, then they are not being compiled by javac or at least, the AST creation phase of javac doesn't understand that a type will be created, and this type can't be used in source code, which makes it impossible to reference the registries from the source code and TP needs it. 

So, I close this issue as there is absolutely nothing that can be done against this issue. We will always have to generate the registries during the last round, unless we assume that there is only one possible round of annotation processing for the inject annotation, which would prevent any other annotation processor to generate code using @Injects.
